"""Add telegram fields and is_admin

Revision ID: ff7f3e9ccfd6
Revises: 88f42f68c99a
Create Date: 2025-10-29 19:53:54.774262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff7f3e9ccfd6'
down_revision: Union[str, Sequence[str], None] = '88f42f68c99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_username', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('tg_first_name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('tg_last_name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'tg_last_name')
    op.drop_column('users', 'tg_first_name')
    op.drop_column('users', 'tg_username')
    # ### end Alembic commands ###
